### ISSUE TITLE
[Suggestion] enemy health circle feedback

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#108]
This might already be something you considered in the past but I always felt the health circle lacked a form of what I only can describe as feedback.

I think hoxhud used to have a red damage circle around the health when damaging/killing enemies.

Here is an example 
![healthcircle](https://user-images.githubusercontent.com/30779314/74609252-a212d780-50e8-11ea-945e-c71f96dc2f27.png)

I would love to implement this myself but I don't have the skills or the knowledge to add it.

Not a big deal but would be really satisfying to see when killing cops.

**Comment by steam-test1** [comment]
Did actually tried it in the past, but couldn't get it to look like hoxhud
It's meant to underdog aced and overkill skill animations
Will try again, as it looks better

**Comment by steam-test1** [comment]
This maybe fixed in the future, as it needs to be rewritten

**Comment by steam-test1** [comment]
Is the following ok
![Untitled44](https://user-images.githubusercontent.com/34393637/77801860-96b0b580-7071-11ea-8cff-38442b4e06c0.png)
The white part stays, but the animation of damage still works

**Comment by LT71** [comment]
That looks good to me, I think the animation itself is the most important part so as long as that works I'd say it's good.

**Comment by steam-test1** [comment]
Managed to fix the damage indicator showing all the time
The next version will be likely released at the end of the week, just in case of a update been released breaking the mod
