### ISSUE TITLE
Issues from the new update

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#135]
The new turret has no health bar visible

**Comment by steam-test1** [comment]
Could you provide a screenshot for the new turret

**Comment by LT71** [comment]
A screenshot like this?

this applies to to both the health circle and the health bar but wolfhuds healthbar works
![20200229143231_1](https://user-images.githubusercontent.com/30779314/75608598-3cb7e100-5b01-11ea-92ac-cdd4d7979b0d.jpg)

Other units work fine as usual
![20200229143256_1](https://user-images.githubusercontent.com/30779314/75608601-404b6800-5b01-11ea-96fd-fc90ac0d6128.jpg)

**Comment by steam-test1** [comment]
![Untitled28](https://user-images.githubusercontent.com/34393637/75608982-8fdb6500-5afc-11ea-822f-ccbafa894f4d.png)
Not encountered that bug, it could be a conflict

**Comment by LT71** [comment]
Very strange, I have no other mods installed. The only thing I can think of right now is that I haven't tried it while being the host since I don't own the latest dlcs. Not that I can see a reason for it to be caused by being a client but its all I got atm.

**Comment by steam-test1** [comment]
Think the issue is there is a check to only to display for the host
The health of turret is still not synced to clients, only the status is synced
