### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#151]
I had a strange crash when playing reservoir dogs. At the end on the card picking screen a player left and the moment they left the game crashed.

Here is the crash report

Application has crashed: C++ exception
mods/VPlusHUD-master/lua/Interaction.lua:687: attempt to index a nil value

SCRIPT STACK

selected_original() lib/units/interactions/interactionext.lua:229
selected() @mods/VPlusHUD-master/lua/Interaction.lua:699
_update_targeted_original() lib/managers/objectinteractionmanager.lua:391
_update_targeted() @mods/VPlusHUD-master/lua/Interaction.lua:711
update_original() lib/managers/objectinteractionmanager.lua:54
update() @mods/VPlusHUD-master/lua/GameInfoManager.lua:2198
update() lib/setups/gamesetup.lua:721
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557

**Comment by steam-test1** [comment]
Added something that may fix the crash

**Comment by LT71** [comment]
haven't been able to recreate the crash since latest update, closing
