### ISSUE TITLE
More weapon stats incompatibility

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#162]
When using vanilla hud with more weapon stats and having burst fire enabled the game will crash when selecting akimbo pistols and smg's. 

It seems to be because of this funcation:
function AkimboWeaponBase:_update_stats_values(...)

The crash  file looks like this:

Application has crashed: C++ exception
[string "lib/managers/menu/menuscenemanager.lua"]:2271: attempt to call method 'set_npc' (a nil value)

SCRIPT STACK

lib/managers/dynamicresourcemanager.lua:220

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name

**Comment by LT71** [comment]
The reason I want to point this out is first of all because of some new cheat mods that has come out and the increasing need of no mutants allowed to keep players in check. No mutants allowed requires more weapon stats to work.

I started with removing the entire AkimboWeaponBase:_update_stats_values function and by doing so the crashes would stop but I thought there might be a better workaround for it

**Comment by steam-test1** [comment]
It happens in WolfHUD as well
If you notify TdlQ they should be able to fix it 
Making a thread on steam forums should be enough

**Comment by steam-test1** [comment]
Update 
Just read TdlQ comments on the mod page and they suggested the following
https://bitbucket.org/pjal3urb/burstfire/src/beta/BurstFire.lua
It's a beta, but it an updated version of burst fire
You can probably delete the steam forum
