### ISSUE TITLE
New driving hud crash

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#176]
Application has crashed: C++ exception
mods/VPlusHUD-master/lua/DrivingHUD.lua:430: attempt to index a nil value

SCRIPT STACK

set_driving_vehicle_state() @mods/VPlusHUD-master/lua/DrivingHUD.lua:583
_update_driving_hud() @mods/VPlusHUD-master/lua/DrivingHUD.lua:548
update() @mods/VPlusHUD-master/lua/DrivingHUD.lua:554
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:878
update() lib/setups/gamesetup.lua:718
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557

**Comment by steam-test1** [comment]
Try the latest commit, if that doesn't work
then the new version of driving HUD from WolfHUD could be added

**Comment by LT71** [comment]
The new update almost works but it has no textures for some mask types

![Untitled](https://user-images.githubusercontent.com/30779314/78258710-ea048700-74fb-11ea-9d3a-2fdfeb9054d1.png)

I could add wolfhuds version and sort out some options if necessary

**Comment by steam-test1** [comment]
The wolfhud one will be more proof, it just needs a setting to change the position of the HUD
