### ISSUE TITLE
new crash

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#180]
Had a crash when i changed from the number display in the options. Crash happen after I restarted the  map and looked at an enemy

Application has crashed: C++ exception
mods/VPlusHUD-master/lua/test2.luac:0: bad argument #1 to 'format' (string expected, got boolean)

@mods/VPlusHUD-master/lua/test2.luac

SCRIPT STACK

set_health() @mods/VPlusHUD-master/lua/test2.luac:0
set_enemy_health() @mods/VPlusHUD-master/lua/test2.luac:0
original() @mods/VPlusHUD-master/lua/test2.luac:0
_update_fwd_ray() @mods/base/req/core/Hooks.lua:260
update_original() lib/units/beings/player/states/playerstandard.lua:432
update_original() @mods/VPlusHUD-master/lua/BurstFire.lua:302
update() @mods/VPlusHUD-master/lua/VanillaHUD.lua:826
original() lib/units/beings/player/playermovement.lua:271
@mods/base/req/core/Hooks.lua:260

**Comment by steam-test1** [comment]
Fixed the crash, but with the option off the following happens
![Untitled47](https://user-images.githubusercontent.com/34393637/78458913-f714a800-76ac-11ea-96da-12da3a5c12ab.png)

**Comment by LT71** [comment]
That's odd, maybe you could just take out the option for now then and have the numbers always display K when in the thousands. Since it looks very nice and clean with less digits.

**Comment by steam-test1** [comment]
Removed the option, it does fix the issue of people not liking the size of the circle
Also converted vehicle health to use the new display
![Untitled48](https://user-images.githubusercontent.com/34393637/78461458-fede4780-76c0-11ea-95f1-5633b678b117.png)

**Comment by LT71** [comment]
That's good but shouldn't the car have 9M at full health? Just based on the health displayed in driving hud.

**Comment by LT71** [comment]
Once the health goes down to 900k it shows the health as 0.9M all the way down to 0.1M. Once the health hits 90k it shows the health as 900K down to 100K.

**Comment by steam-test1** [comment]
![Untitled48](https://user-images.githubusercontent.com/34393637/78472966-f9bae000-7734-11ea-9e78-ca2d61715069.png)
It should function correctly now
![Untitled49](https://user-images.githubusercontent.com/34393637/78472971-017a8480-7735-11ea-949f-995fe88e4f40.png)

**Comment by LT71** [comment]
looks good
