### ISSUE TITLE
Hudlist equipment issue

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#188]
Suddenly I can't see ammo bags, medic bags etc on the hud. Not really sure whats wrong with it since it has worked in the past..

**Comment by steam-test1** [comment]
Can't reproduce
Probably a mod conflict, maybe check logs

**Comment by LT71** [comment]
This is such a strange thing, I only have the hud currently, logs says nothing but I remade the whole hudlist by getting the one from wolfhud then adding in every single update that has been done to the hudlist in vanillahud and then the equipment show up. Yet if I use the exactly same hudlist file that comes with the download from here it wont work.

**Comment by LT71** [comment]
Well this is indeed not an issue, I must have done something on my end
