### ISSUE TITLE
Healthcircle negative value

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#189]
This has nothing to do with the latest update to it because I have seen it for a long time just never bothered to report it since how rare it is. Sometimes enemies seem to have negative health which is a little odd.

![Untitled](https://user-images.githubusercontent.com/30779314/78506304-e16cb480-7778-11ea-8b67-dd88ea644e0b.png)

**Comment by steam-test1** [comment]
Just testing a fix as the enemy health bar already includes a fix for that issue

**Comment by LT71** [comment]
It happened using the latest version, but so far that's the only time I have seen it happen since updating

**Comment by LT71** [comment]
will reopen if issue persists
