### ISSUE TITLE
PDTH Hud

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#191]
The new burstfire is not compatible with pdth hud

Application has crashed: C++ exception
mods/VPlusHUD-master/lua/BurstFire.lua:370: attempt to index a nil value

SCRIPT STACK

set_teammate_weapon_firemode_custom() @mods/VPlusHUD-master/lua/BurstFire.lua:358
_check_action_weapon_firemode() @mods/VPlusHUD-master/lua/BurstFire.lua:334
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:932
update_original() lib/units/beings/player/states/playerstandard.lua:435
update() @mods/VPlusHUD-master/lua/BurstFire.lua:302
original() lib/units/beings/player/playermovement.lua:271
@mods/base/req/core/Hooks.lua:260

**Comment by steam-test1** [comment]
Could you try adding the following in PDTH HUD teammate
```
--Default function for vanilla HUD. If using a custom HUD that alters fire mode HUD components, make sure to implement this function in it
	HUDTeammate.set_weapon_firemode_custom = HUDTeammate.set_weapon_firemode_custom or function(self, id)
		local weapon_selection
		
		if id == 1 then
			weapon_selection = self._player_panel:child("weapons_panel"):child("secondary_weapon_panel"):child("weapon_selection")
		else
			weapon_selection = self._player_panel:child("weapons_panel"):child("primary_weapon_panel"):child("weapon_selection")
		end

		if alive(weapon_selection) then
			local firemode_single = weapon_selection:child("firemode_single")
			local firemode_auto = weapon_selection:child("firemode_auto")
			if alive(firemode_single) and alive(firemode_auto) then
				firemode_single:show()
				firemode_auto:show()
			end
		end
	end
```
If it works I will add it in the next update

**Comment by LT71** [comment]
I added it in but I still got the same crash

**Comment by LT71** [comment]
latest update results in this crash:

Application has crashed: C++ exception
mods/VPlusHUD-master/lua/BurstFire.lua:370: attempt to index local 'primary_weapon_panel' (a nil value)



SCRIPT STACK

set_teammate_weapon_firemode_custom() @mods/VPlusHUD-master/lua/BurstFire.lua:358
_check_action_weapon_firemode() @mods/VPlusHUD-master/lua/BurstFire.lua:334
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:932
update_original() lib/units/beings/player/states/playerstandard.lua:435
update() @mods/VPlusHUD-master/lua/BurstFire.lua:302
original() lib/units/beings/player/playermovement.lua:271
@mods/base/req/core/Hooks.lua:260

**Comment by steam-test1** [comment]
PDTH HUD has code for burst fire

**Comment by steam-test1** [comment]
Fixed it
In PDTH HUD teammate change `set_firemode_burst` function to `set_weapon_firemode_custom`
Tested it and it works
I will update PDTH HUD at sometime in the future

**Comment by LT71** [comment]
Great!
