### ISSUE TITLE
Buff height option

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#192]
Just a heads up that currently the buff height option will also move the subtitles since they are moved based on where the buff icons are.

**Comment by LT71** [comment]
i think this could be fixed with a very simple edit to prevent the subtitles from moving when the buff offset passes a set value since it would no longer be needed to move out of the way.

One problem I'm facing on my end is that if I change the offset while in game its reversed where a high value displays the buff list lower on the screen while a low value puts the list up top.

**Comment by steam-test1** [comment]
I decided to disable the offset as it was mainly kept for MUI
So the position can be moved like in HUDList

**Comment by LT71** [comment]
The subtitles and buffs will overlap but users will just have to move the list to about 150 in order to have to list on top of the subtitles. Gonna look a little worse for buff list users since they will need to have all those buffs closer the center of the screen instead of the bottom. 

Compared to having the subtitles closer the center which only are visible now and then but I'm no buff list user myself and moving the buff list instead of the subs make things much more simple.

Not gonna but too much thought into it as long as it works.
