### ISSUE TITLE
Health indicator

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#201]
I don't know if this issue is from the latest update but at the moment the health info seems a bit weird. Sometimes when I look at an enemy (in my case stealth) the health circle will fade once i stop looking and will then flash the health number on the screen afterwards. 

I don't recall it being like that before but I'm not sure.

**Comment by LT71** [comment]
It also seems to be stuck on the screen when starting a heist

**Comment by steam-test1** [comment]
Noticed that too, Will fix in the next update
