### ISSUE TITLE
The new tab info

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#207]
Is there any chance the new tab stats info could make it into the hud? I haven't tested the latest update but being able to know total pagers when joining into a game must be useful. 

I also think the new convert counter is a great addition, maybe have  the joker count simply replacing the body bag info when a heist goes loud?

**Comment by steam-test1** [comment]
The pager counter changes to the convert counter in loud
So it allow takes up a little space

**Comment by steam-test1** [comment]
Added in latest commit
