### ISSUE TITLE
Tab stats challenge overlapping

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#213]
It looks like the challenges overlap the extended inventory

![Untitled](https://user-images.githubusercontent.com/30779314/82148226-41b04500-9853-11ea-8ead-53a485f7606d.png)

![Untitled2](https://user-images.githubusercontent.com/30779314/82148229-4543cc00-9853-11ea-8b6b-37a808a548dd.png)

Is there a way to limit how many challenges that can be visible?
I think having a limit of 3 at once would make it look cleaner, I just don't know how to make that work.

![Untitled3](https://user-images.githubusercontent.com/30779314/82148245-5987c900-9853-11ea-8db2-bab980a4e96d.png)

**Comment by steam-test1** [comment]
You could try reducing the header text size to the same as the track playing size
Will look into it at a later
