### ISSUE TITLE
Stoic Perkdeck Visual Bug

### ISSUE THREAD

**Issue by c0derMo** [steam-test1/VPlusHUD#219]
Sometimes (most of the times when I'm joining heists midway), I get an armor bar, eventhough I have the Stoic Perkdeck maxed (so all my armor gets converted to health.
That alone wouldn't be a huge issue, however, the "stripes", which usually display on the health bar, and symbolise my damage-over-time that I will take, are not shown on the healthbar, and are almost invisibly displayed on the armor bar.

I don't think I ever had this bug appear when I started a day/heist, I think it only appears when I'm dropping in.
If needed I'll try to get a screenshot of this.

I don't have any other HUD mods installed.

**Comment by steam-test1** [comment]
Will look into it, but may not be fixable
