### ISSUE TITLE
Crash on heist start (Linux)

### ISSUE THREAD

**Issue by TheMasterOfChaos** [steam-test1/VPlusHUD#224]
Without HUD all works fine, but with HUD game always crashes on heist start and less often on loading.
[crash.txt](https://github.com/steam-test1/VPlusHUD/files/5806624/crash.txt)

[2021_01_13_log.txt](https://github.com/steam-test1/VPlusHUD/files/5806626/2021_01_13_log.txt)

**Comment by steam-test1** [comment]
In the damage popup options uncheck Windows Compatibility
That should fix the crash

**Comment by TheMasterOfChaos** [comment]
Thank you for help, but game crashes with the same fatal error

**Comment by TheMasterOfChaos** [comment]
I'm very sorry for wasting your time, i've made a mistake in installing SuperBLT. Re-install fixed the problem
