### ISSUE TITLE
linux native crashes on new versions

### ISSUE THREAD

**Issue by mixeerse** [steam-test1/VPlusHUD#229]
Version 2.1.8.2 doesn't crash my game, however the newest update crashes whenever I shoot my gun on any heist. Haven't tried any versions inbetween.

**Comment by steam-test1** [comment]
Could post your log file as that should contain your crashlog on Linux

**Comment by mixeerse** [comment]
[2021_05_03_log.txt](https://github.com/steam-test1/VPlusHUD/files/6414439/2021_05_03_log.txt)
[crash.txt](https://github.com/steam-test1/VPlusHUD/files/6414440/crash.txt)
The crash occurs whenever I hit any enemy, not just shoot actually.
Have the damage popups completely disabled and the windows compatibility unchecked.

**Comment by steam-test1** [comment]
Fixed in V2.1.8.3.6, also the damage popups should now function on Linux
