### ISSUE TITLE
You don't receive Tag Team heals

### ISSUE THREAD

**Issue by metenn** [steam-test1/VPlusHUD#234]
I've noticed and tested that if you use VanillaHUD+, if someone tags you as Tag Team, you don't get health from kills.    
I'm pretty sure the same applies to damage absorption, though I could only confirm that from the visual part by looking at VanHud+ players' healthbars in public lobbies.

Interestingly the issue also persists on WolfHUD.

**Comment by steam-test1** [comment]
Pushed out an update that may fix this issue

**Comment by metenn** [comment]
Great, I'll check it out with someone who has an updated version.

**Comment by metenn** [comment]
Fixed by the way.
