### ISSUE TITLE
Crash when launching a heist

### ISSUE THREAD

**Issue by HairyMilkshakes** [steam-test1/VPlusHUD#235]
Here's what's in the dump file:

Comment: 'Application has crashed: C++ exception
[string "lib/managers/hud/hudchat.lua"]:133: attempt to index local 'say' (a nil value)

SCRIPT STACK

original() @mods/Chat Translator/main.lua:625
init() @mods/base/req/core/Hooks.lua:188
new() core/lib/utils/coreclass.lua:35
_create_hud_chat() lib/managers/hudmanagerpd2.lua:693
original() lib/managers/hudmanagerpd2.lua:664
_setup_player_info_hud_pd2_original() @mods/base/req/core/Hooks.lua:188
_setup_player_info_hud_pd2_original() @mods/VanillaHUD Plus/lua/HUDList.lua:113
_setup_player_info_hud_pd2_original() @mods/VanillaHUD Plus/lua/DrivingHUD.lua:939
_setup_player_info_hud_pd2() @mods/VanillaHUD Plus/lua/EnemyHealthCircle.lua:6
setup() 4
setup() lib/managers/hudmanager.lua:330
load_hud() lib/managers/hudmanager.lua:317
init_finalize() lib/managers/hudmanager.lua:219
init_finalize() lib/setups/gamesetup.lua:707
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:442

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap

**Comment by kosavsech** [comment]
I don't think this is bcuz of VanillaHudPlus

**Comment by HairyMilkshakes** [comment]
How can I find the cause using the dump file, or do I need to provide that here?

**Comment by HairyMilkshakes** [comment]
Turns out Chat Translator: https://modworkshop.net/mod/29967 is incompatible even with the Ultrawide fix.
