### ISSUE TITLE
crashed during the event

### ISSUE THREAD

**Issue by DazAttack** [steam-test1/VPlusHUD#244]
Application has crashed: C++ exception
[string "lib/managers/playermanager.lua"]:278: attempt to index a nil value

SCRIPT STACK

set_damage_absorption() lib/managers/playermanager.lua:288
sync_hostage_headcount_original() lib/managers/group_ai_states/groupaistatebase.lua:4114
sync_hostage_headcount() @mods/VanillaHUD Plus/lua/GameInfoManager.lua:1993
update() @mods/Void UI/lua/hud/HudAssaultCorner.lua:1635
update() lib/managers/group_ai_states/groupaistatebesiege.lua:47
update() lib/managers/groupaimanager.lua:23
original() lib/setups/gamesetup.lua:755
update() @mods/base/req/core/Hooks.lua:265
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.112.51
	CPU : AMD Ryzen 7 2700 Eight-Core Processor (8 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : AMD Radeon RX 5700 XT / aticfx32.dll[30.0.13025.5005]
	Language : english
	Memory :     16335MB 76KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by steam-test1** [comment]
Fixed in the latest Void UI update
