### ISSUE TITLE
Localization strings enemies not works

### ISSUE THREAD

**Issue by chromKa** [steam-test1/VPlusHUD#289]
132-196 strings not works, in russian - only english strings.

**Comment by steam-test1** [comment]
Fixed in the latest auto update

**Comment by chromKa** [comment]
ye, works!

**Comment by steam-test1** [comment]
I know I fixed this, but the reason it was in English is because HopLib doesn't have a Russian translation
https://github.com/segabl/pd2-hoplib
If it was translated to Russian it would help, as my fix broke other translations
It's up to you though if you want to or not

**Comment by chromKa** [comment]
OK, I'll translate it into Russian

**Comment by steam-test1** [comment]
Thanks

**Comment by chromKa** [comment]
https://github.com/segabl/pd2-hoplib/pull/22

**Comment by steam-test1** [comment]
Thanks updated the HUD
