### ISSUE TITLE
The latest version is crashing

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#29]
I am getting this crash when loading into a heist, I havent looked into it yet.

Application has crashed: C++ exception
mods/VPlusHUD-master/lua/VanillaHUD.lua:428: attempt to call method 'set_right' (a nil value)

SCRIPT STACK

init_original() @mods/VPlusHUD-master/lua/VanillaHUD.lua:148
original() @mods/VPlusHUD-master/lua/KillCounter.lua:230
init() @mods/base/req/core/Hooks.lua:260
new() core/lib/utils/coreclass.lua:35
_create_teammates_panel() lib/managers/hudmanagerpd2.lua:981
_setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:647
_setup_player_info_hud_pd2_original() @mods/VPlusHUD-master/lua/HUDList.lua:113
_setup_player_info_hud_pd2_original() @mods/VPlusHUD-master/lua/DrivingHUD.lua:497
_setup_player_info_hud_pd2_original() @mods/Hud Collection/EcmTimer/hudmanagerpd2.lua:59
_setup_player_info_hud_pd2_original() @mods/BangHUD/Lua/HUDManagerPD2.lua:13
_setup_player_info_hud_pd2() @mods/VPlusHUD-master/lua/EnemyHealthbar.lua:6
setup() 4
setup() lib/managers/hudmanager.lua:330
load_hud() lib/managers/hudmanager.lua:317
init_finalize() lib/managers/hudmanager.lua:219
init_fin_orig() lib/setups/gamesetup.lua:680
init_finalize() @mods/The Fixes/gamesetup.lua:13
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:441

**Comment by steam-test1** [comment]
Fixed
