### ISSUE TITLE
ECM HUD breaks if ECM disappears

### ISSUE THREAD

**Issue by vadcx** [steam-test1/VPlusHUD#293]
Reproduce:

1. Place ECM on a breakable surface such as glass
2. Shoot the glass to remove the ECM as a game object
3. The ECM HUD stops from updating but remains there, frozen

Interestingly, it begins blinking color (red color fade) so the Vanilla+ HUD detects something but doesn't remove the vanished ECM from display. If memory serves me right, this is an ancient one, dating back to HoxHud days.

Test map: GO Bank probably. I'm witnessing this on Election Day, Day 2 (ECM placed on rear van window).

**Comment by steam-test1** [comment]
This should be fixed in .41 update
