### ISSUE TITLE
bullet storm crash

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#31]
Going into custody while the bulletstorm is active will case the following crash:
It wont matter if the bulletstorm icon is on or not

Application has crashed: C++ exception
mods/VPlusHUD-master/lua/VanillaHUD.lua:826: attempt to index a nil value

SCRIPT STACK

_update_queued_tasks() lib/managers/enemymanager.lua:608
update() lib/managers/enemymanager.lua:51
update() lib/setups/gamesetup.lua:720
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:556

**Comment by LT71** [comment]
I'm checking with eightan if he got an updated version of it

**Comment by LT71** [comment]
the line is at 818 in the latest build

**Comment by steam-test1** [comment]
Fixed in latest commit
