### ISSUE TITLE
Armor timer stuck when revived

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#44]
The armor timer shows a static value after being helped back up

**Comment by LT71** [comment]
I have been trying all kinds of things for this, can't seem to find a fix on my own.
If you can't find a way to fix or don't want to fix it then we can close this and probably update the modworkshop version.

**Comment by steam-test1** [comment]
The original code is from HoxHUD
The bug was present in JackHUD and later SydneyHUD
UHUD+ Plus made a version with different code, but with the same issue
