### ISSUE TITLE
About the contract heat

### ISSUE THREAD

**Issue by LT71** [steam-test1/VPlusHUD#92]
This is more a question regarding the newly added contract heat in the contract broker.

I have been messing around with it a bit and to me it doesn't make much sense to show the xp bonus in the contract broker menu.

This is because the xp boost only applies to contracts that are taken from crimenet. If you buy the contract yourself from the contract broker the heat bonus wont apply and this is intended to probably have people pick heists they rarely play from the crimenet as they pop up.

I just thought it might be adding confusion more than help to see a heat bonus that wont apply.

However the xp reduction does apply and fits perfectly well and even more so after my edit that imo gives a more accurate display.

So I thought it might be a better idea to take out the heat bonus and just keep the xp reduction but with this information I let you decide on it.

**Comment by steam-test1** [comment]
Was aware, but it can still be useful know what heists have the bonus as you need to complete them to lower the minus heat more quickly
Maybe adding an option, then the player can decide
